### ISSUE TITLE
Reenable OSX on the environments matrix

### ISSUE THREAD

**Issue by juanpaucar** [stackbuilders/hapistrano#152]
As mentioned on https://github.com/stackbuilders/hapistrano/pull/151. The build was failing on CI for macOS because brew was not able to find `cabal` and `ghc`. We need to spend some time checking why the failure if both packages are still available on the brew index.

**Comment by mauriciofierrom** [comment]
Between the previous commit and #151 version [2.6.0](https://brew.sh/2020/12/01/homebrew-2.6.0/) of Homebrew dropped support for macOS 10.13 (High Sierra) which is the [default version](https://docs.travis-ci.com/user/reference/osx#macos-version) used by TravisCI workers if the `osx_image` field isn't specified. Since (apparently) Apple no longer supports High Sierra either, it might be a good idea to drop support for that platform.

I briefly [tested](https://github.com/mauriciofierrom/hapistrano/commit/8717789a42a72949d1892088e5859662ad54b473#diff-6ac3f79fc25d95cd1e3d51da53a4b21b939437392578a35ae8cd6d5366ca5485R30) using `xcode11` and the [build passes OK](https://travis-ci.org/github/mauriciofierrom/hapistrano/jobs/763990486). I hope that's useful.

**Comment by juanpaucar** [comment]
Thank you very much @mauriciofierrom
