### ISSUE TITLE
Replace Dockerfile base with distroless

### ISSUE THREAD

**Issue by sestrella** [stackbuilders/hapistrano#182]
Taking the [Distroless Rust](https://github.com/GoogleContainerTools/distroless/blob/main/examples/rust/Dockerfile) example as a reference, the existing `Dockerfile` could be split into different stages:

- One that compiles the project and generates a binary
- Another one that places that binary in a distroless image

The outcome would be a very tiny image. Taking into account that `hapistrano` is a deployment tool that is mostly executed by a CI pipeline, shrinking the image is beneficial since it would reduce the overhead produced by pulling the image from Docker Hub to the CI worker.

**Comment by FranzGB** [comment]
> Hey @FranzGB I think you've been working on this issue lately. Any comments/questions so far?

Hey Cristhian. Yes, I am working on this still! I used a Distroless base for hapistrano I am having trouble testing if it worked.

**Comment by CristhianMotoche** [comment]
Hey @sestrella. @FranzGB has been working on this in #220 but I think I faced a blocker and that is the fact that Hapistrano executes `ssh` (and maybe others, too) from the host machine. In this case, the distroless images won't have the `ssh` command and we'll get an error as the one that I [mention here](https://github.com/stackbuilders/hapistrano/pull/220#issuecomment-1569362565). Please, let us know if there is anything that we're missing in order to continue with this.

**Comment by CristhianMotoche** [comment]
Hey @sestrella I was wondering if you know about a possible way to overcome the issues that we faced in @FranzGB's PR. Should we look for a different distro? Perhaps a small distribution? Let me know. Otherwise, we may not be able to solve this issue and we could close it.

**Comment by CristhianMotoche** [comment]
Hey @sestrella We're using the `alpine` image which is very small ~5MB. Although, I see the hapistrano image is ~73MB, which I think was the motivation for this issue:

```
REPOSITORY                         TAG        IMAGE ID       CREATED        SIZE
alpine                             3.15       59be8124109e   5 weeks ago    5.34MB
ghcr.io/stackbuilders/hapistrano   v0.4.8.0   26c1a98bb4d2   5 months ago   73.1MB
```

The [hapistrano binary](https://github.com/stackbuilders/hapistrano/releases/tag/v0.4.8.0) is kind of big (~44MB) and maybe that's the reason the image is kind of big. So, I don't think this is a matter of the base image that we use but the size of the binary file. Would it make sense to create a new issue to address that instead of moving into a distroless base image? WDYT?
