### ISSUE TITLE
Comparison to keter?

### ISSUE THREAD

**Issue by ajnsit** [stackbuilders/hapistrano#40]
This project is interesting! How does it compare to something like Keter (https://github.com/snoyberg/keter)?

**Comment by jsl** [comment]
Not too familiar with Keter, but based on the README, it seems like overall, the main difference is that Keter does a lot more than Hapistrano. Some of the features that Keter has but hapistrano doesn't include:

1. reverse proxying
2. ssl support
3. relaunching processes that die
4. log file management
5. postgres management

I'm a bit skeptical that an application server should handle all of these items, rather than delegating them to dedicated utilities on Linux systems, but perhaps that's just because I haven't looked that closely at Keter - it could be great at all of these items and I'm really not familiar enough to judge it.

Hapistrano really takes charge of getting code to servers (efficiently, using a git cache), building,  restarting the application, and rollback. Activation of new applications is done by switching a symlink after the build is done, so it's pretty fast. All of the items in the list above are delegated to Linux utilities that are designed for that purpose (nginx for 1 and 2, Linux daemon management for 3, logrotate for 4, and whatever you want for 5 - some of our projects have used things like flyway). Hapistrano could be replaced by a 20-line shell script.

I believe that Keter deploys binaries. Hapistrano builds on the target system (and we use Stack for quick builds in most cases, but that's optional). This is a disadvantage from a security perspective since you need to keep the build utilities on the server, but an advantage in the sense that you don't have to worry about linking issues and binary format. Also, for years we haven't worried too much about development toolkits being on the server for Python and Ruby apps, so that isn't my top concern with many applications for security.

Hapistrano is basically just a simple collection of shell commands that clone a repo, build, and switch symlinks at the end of the process to activate the new application. It is modeled after Ruby's Capistrano, and steals most of its name to make this relationship clear. In contrast, (and correct me if I'm wrong), Keter seems more like a Java Jetty server.

Hapistrano is very simple, and hasn't had much development effort put into it. It is missing functionality like deploying concurrently to multi-server systems, and may have other bugs. I would guess that Keter is much more battle-tested, although we use Hapistrano for a few production applications and haven't had a problem.

I would be much more inclined to use Keter if 1. we wanted a full-featured application server that handles the areas that Keter addresses 2. were worried about security issues of having a build toolchain on servers.

Hope this helps! Please feel free to add any clarifications about Keter or other questions.

**Comment by ajnsit** [comment]
Ah so hapistrano is more of a code transfer and build wrapper. Whereas keter is strictly a production server management tool. It provides easy deployments (Just scp over a binary, which is automatically detected and deployed, and logs rotated). The reverse proxy bits are also useful as it means I don't need to maintain nginx as well.

It seems that keter and hapistrano are mostly orthogonal then. I should, for example, be able to use hapistrano to deploy and test my code on staging and then ship a binary off to the production server where keter takes over.

It would perhaps be interesting to explore better compatibility between the two tools, so such a workflow works out of the box.

**Comment by jsl** [comment]
Closing since this has been inactive for a while. I'd be happy to explore improving compatibility in a separate issue or PR.
