### ISSUE TITLE
Add the ability to copy compiled files from CI

### ISSUE THREAD

**Issue by mrkkrp** [stackbuilders/hapistrano#54]
It's a known fact that with some projects we're running into issues by compiling on server. For example, V********, if compiled with optimizations, exhausts all available memory and can't finish anymore. It may be impossible to deploy it with Hapistrano even without optimizations after a while. I think there are other projects that suffer from this. For these cases, we need an option to copy pre-compiled files from CI or from a local directory in general, because files compiled on CI are often suitable for runnnig on target server. In any case, the feature is nice to have.

**Comment by lpaulmp** [comment]
This feature will help a lot of projects and will reduce tons of time compiling in case that you need compatibility   [buildkite](https://buildkite.com/) could help in that sense.. Thanks @mrkkrp for open this issue

**Comment by jsl** [comment]
@mrkkrp I agree that this feature would be nice to have. 

I'm ok as long as we leave the option to compile on the server as well, since the architecture and linking is not always guaranteed to be the same on CI and staging/prod. My thought is that differences there may lead to run-time errors, and avoiding run-time errors is why we're using Haskell in the first place in many cases. 

FWIW, we should be able to take care of lack of memory issues with just a couple of commands by adding more swap. We may be able to also take care of the compile interfering with production traffic by setting a lower process priority for the build.

At any rate, this feature would be nice.

**Comment by mrkkrp** [comment]
Yeah, my idea that it will be optional, so when you really need it, you can reach for it.

**Comment by sestrella** [comment]
@mrkkrp Maybe we could start by copying `.stack-work` directory across releases:

Let's say we have the following folder structure

```
current -> releases/20170202
releases
  20170202
    .stack-work # copy from 20170201
  20170201
    .stack-work
```

So during the deployment process we could copy `.stack-work` directory from previous release `20170201` to new release `20170202` before we trigger the build script. 

Going further I think this functionality is kind of similar as the [shared folder](http://capistranorb.com/documentation/getting-started/structure/) from capistrano. But instead of symlinking the files on `shared` folder after the build, we need to copy folders from the previous release to the new one as a pre-build tasks.

Ideally, folders to be copy from previous releases should be configurable. That way we don't tie our implementation to only stack projects.

@mrkkrp, @jsl, @lpaulmp What do you guys think?

**Comment by lpaulmp** [comment]
@sestrella what do you think instead of copy the .stack-work just link it from another folder for instance `shared forlder`, since link is faster than copy. This future shouldn't be a nice to have, this should be part of the normal process I think. Lets open other issues to with this idea.

**Comment by sestrella** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [hapistrano - Add the ability to copy compiled files from CI](https://trello.com/c/1CGPHVdX/6-hapistrano-add-the-ability-to-copy-compiled-files-from-ci)
