### ISSUE TITLE
Is cloning necessary when `copy_files` is included

### ISSUE THREAD

**Issue by psibi** [stackbuilders/hapistrano#65]
In our work, we do *most* of the deployment just by copying the binaries.

hapistrano seems to do a bare clone always. Is there any reason why it is done like this ?

**Comment by mrkkrp** [comment]
I think the reason is that we often want to run the app with current directory that is root of the repo, which contains configuration files and some other stuff. Note that we have caching for clonning: we keep a clone of the repo and subsequent deploys first refresh it (which is faster than full clonning every time), then use it to create a release. From my experience clonning is not taking long and is not a bottleneck of any sort. The answer to the question whether it's truly necessary is *"it depends"*, as it's something that may vary on per-project basis.

**Comment by psibi** [comment]
Ah, okay. Because of the cloning, we have to do mandatory setup of SSH Forwarding for git authentication to make hapistrano work. That was not required in our in-house haskell scripts which we are using right now for deployment.

**Comment by psibi** [comment]
@mrkkrp 

Can we have an optional `--no-clone` option ?

Something like `hap deploy --no-clone` or rather have it defined in the configuration file ?

If others agree with the idea, I can work on the PR.

**Comment by mrkkrp** [comment]
I tihnk we can add such an option now that we allow copying files and directories. Any thoughts @sestrella, @jsl?

**Comment by jsl** [comment]
Hi @psibi - so the idea would be that it does the binary copy, and does symlink updating etc. as in the current system (to activate the next release), but without the clone? I think that would be fine, and it seems like a complementary feature to the current codebase. PRs welcome!

**Comment by psibi** [comment]
Yeah, something like that. I will use the patched version of the package one or two days in our production systems and then will submit the PR when we are satisfied with the workflow. We can take it from there, I guess. Thanks.
